package monitor.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepBirouteLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public DepBirouteLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNull() {
            addCriterion("MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNotNull() {
            addCriterion("MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMsgIdEqualTo(String value) {
            addCriterion("MSG_ID =", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotEqualTo(String value) {
            addCriterion("MSG_ID <>", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThan(String value) {
            addCriterion("MSG_ID >", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_ID >=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThan(String value) {
            addCriterion("MSG_ID <", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThanOrEqualTo(String value) {
            addCriterion("MSG_ID <=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLike(String value) {
            addCriterion("MSG_ID like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotLike(String value) {
            addCriterion("MSG_ID not like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdIn(List<String> values) {
            addCriterion("MSG_ID in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotIn(List<String> values) {
            addCriterion("MSG_ID not in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdBetween(String value1, String value2) {
            addCriterion("MSG_ID between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotBetween(String value1, String value2) {
            addCriterion("MSG_ID not between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgFromIsNull() {
            addCriterion("MSG_FROM is null");
            return (Criteria) this;
        }

        public Criteria andMsgFromIsNotNull() {
            addCriterion("MSG_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andMsgFromEqualTo(String value) {
            addCriterion("MSG_FROM =", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromNotEqualTo(String value) {
            addCriterion("MSG_FROM <>", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromGreaterThan(String value) {
            addCriterion("MSG_FROM >", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_FROM >=", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromLessThan(String value) {
            addCriterion("MSG_FROM <", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromLessThanOrEqualTo(String value) {
            addCriterion("MSG_FROM <=", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromLike(String value) {
            addCriterion("MSG_FROM like", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromNotLike(String value) {
            addCriterion("MSG_FROM not like", value, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromIn(List<String> values) {
            addCriterion("MSG_FROM in", values, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromNotIn(List<String> values) {
            addCriterion("MSG_FROM not in", values, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromBetween(String value1, String value2) {
            addCriterion("MSG_FROM between", value1, value2, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgFromNotBetween(String value1, String value2) {
            addCriterion("MSG_FROM not between", value1, value2, "msgFrom");
            return (Criteria) this;
        }

        public Criteria andMsgToIsNull() {
            addCriterion("MSG_TO is null");
            return (Criteria) this;
        }

        public Criteria andMsgToIsNotNull() {
            addCriterion("MSG_TO is not null");
            return (Criteria) this;
        }

        public Criteria andMsgToEqualTo(String value) {
            addCriterion("MSG_TO =", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToNotEqualTo(String value) {
            addCriterion("MSG_TO <>", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToGreaterThan(String value) {
            addCriterion("MSG_TO >", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_TO >=", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToLessThan(String value) {
            addCriterion("MSG_TO <", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToLessThanOrEqualTo(String value) {
            addCriterion("MSG_TO <=", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToLike(String value) {
            addCriterion("MSG_TO like", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToNotLike(String value) {
            addCriterion("MSG_TO not like", value, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToIn(List<String> values) {
            addCriterion("MSG_TO in", values, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToNotIn(List<String> values) {
            addCriterion("MSG_TO not in", values, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToBetween(String value1, String value2) {
            addCriterion("MSG_TO between", value1, value2, "msgTo");
            return (Criteria) this;
        }

        public Criteria andMsgToNotBetween(String value1, String value2) {
            addCriterion("MSG_TO not between", value1, value2, "msgTo");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrIsNull() {
            addCriterion("CURRENT_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrIsNotNull() {
            addCriterion("CURRENT_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrEqualTo(String value) {
            addCriterion("CURRENT_ADDR =", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrNotEqualTo(String value) {
            addCriterion("CURRENT_ADDR <>", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrGreaterThan(String value) {
            addCriterion("CURRENT_ADDR >", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_ADDR >=", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrLessThan(String value) {
            addCriterion("CURRENT_ADDR <", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_ADDR <=", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrLike(String value) {
            addCriterion("CURRENT_ADDR like", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrNotLike(String value) {
            addCriterion("CURRENT_ADDR not like", value, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrIn(List<String> values) {
            addCriterion("CURRENT_ADDR in", values, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrNotIn(List<String> values) {
            addCriterion("CURRENT_ADDR not in", values, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrBetween(String value1, String value2) {
            addCriterion("CURRENT_ADDR between", value1, value2, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andCurrentAddrNotBetween(String value1, String value2) {
            addCriterion("CURRENT_ADDR not between", value1, value2, "currentAddr");
            return (Criteria) this;
        }

        public Criteria andIsArriveIsNull() {
            addCriterion("IS_ARRIVE is null");
            return (Criteria) this;
        }

        public Criteria andIsArriveIsNotNull() {
            addCriterion("IS_ARRIVE is not null");
            return (Criteria) this;
        }

        public Criteria andIsArriveEqualTo(String value) {
            addCriterion("IS_ARRIVE =", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveNotEqualTo(String value) {
            addCriterion("IS_ARRIVE <>", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveGreaterThan(String value) {
            addCriterion("IS_ARRIVE >", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ARRIVE >=", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveLessThan(String value) {
            addCriterion("IS_ARRIVE <", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveLessThanOrEqualTo(String value) {
            addCriterion("IS_ARRIVE <=", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveLike(String value) {
            addCriterion("IS_ARRIVE like", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveNotLike(String value) {
            addCriterion("IS_ARRIVE not like", value, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveIn(List<String> values) {
            addCriterion("IS_ARRIVE in", values, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveNotIn(List<String> values) {
            addCriterion("IS_ARRIVE not in", values, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveBetween(String value1, String value2) {
            addCriterion("IS_ARRIVE between", value1, value2, "isArrive");
            return (Criteria) this;
        }

        public Criteria andIsArriveNotBetween(String value1, String value2) {
            addCriterion("IS_ARRIVE not between", value1, value2, "isArrive");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeIsNull() {
            addCriterion("MSG_RTNCODE is null");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeIsNotNull() {
            addCriterion("MSG_RTNCODE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeEqualTo(String value) {
            addCriterion("MSG_RTNCODE =", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeNotEqualTo(String value) {
            addCriterion("MSG_RTNCODE <>", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeGreaterThan(String value) {
            addCriterion("MSG_RTNCODE >", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_RTNCODE >=", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeLessThan(String value) {
            addCriterion("MSG_RTNCODE <", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeLessThanOrEqualTo(String value) {
            addCriterion("MSG_RTNCODE <=", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeLike(String value) {
            addCriterion("MSG_RTNCODE like", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeNotLike(String value) {
            addCriterion("MSG_RTNCODE not like", value, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeIn(List<String> values) {
            addCriterion("MSG_RTNCODE in", values, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeNotIn(List<String> values) {
            addCriterion("MSG_RTNCODE not in", values, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeBetween(String value1, String value2) {
            addCriterion("MSG_RTNCODE between", value1, value2, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andMsgRtncodeNotBetween(String value1, String value2) {
            addCriterion("MSG_RTNCODE not between", value1, value2, "msgRtncode");
            return (Criteria) this;
        }

        public Criteria andCorralationIdIsNull() {
            addCriterion("CORRALATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andCorralationIdIsNotNull() {
            addCriterion("CORRALATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCorralationIdEqualTo(String value) {
            addCriterion("CORRALATION_ID =", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdNotEqualTo(String value) {
            addCriterion("CORRALATION_ID <>", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdGreaterThan(String value) {
            addCriterion("CORRALATION_ID >", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdGreaterThanOrEqualTo(String value) {
            addCriterion("CORRALATION_ID >=", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdLessThan(String value) {
            addCriterion("CORRALATION_ID <", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdLessThanOrEqualTo(String value) {
            addCriterion("CORRALATION_ID <=", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdLike(String value) {
            addCriterion("CORRALATION_ID like", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdNotLike(String value) {
            addCriterion("CORRALATION_ID not like", value, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdIn(List<String> values) {
            addCriterion("CORRALATION_ID in", values, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdNotIn(List<String> values) {
            addCriterion("CORRALATION_ID not in", values, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdBetween(String value1, String value2) {
            addCriterion("CORRALATION_ID between", value1, value2, "corralationId");
            return (Criteria) this;
        }

        public Criteria andCorralationIdNotBetween(String value1, String value2) {
            addCriterion("CORRALATION_ID not between", value1, value2, "corralationId");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNull() {
            addCriterion("MSG_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNotNull() {
            addCriterion("MSG_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeEqualTo(String value) {
            addCriterion("MSG_TYPE =", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotEqualTo(String value) {
            addCriterion("MSG_TYPE <>", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThan(String value) {
            addCriterion("MSG_TYPE >", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE >=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThan(String value) {
            addCriterion("MSG_TYPE <", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE <=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLike(String value) {
            addCriterion("MSG_TYPE like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotLike(String value) {
            addCriterion("MSG_TYPE not like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIn(List<String> values) {
            addCriterion("MSG_TYPE in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotIn(List<String> values) {
            addCriterion("MSG_TYPE not in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeBetween(String value1, String value2) {
            addCriterion("MSG_TYPE between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotBetween(String value1, String value2) {
            addCriterion("MSG_TYPE not between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andDownStatusIsNull() {
            addCriterion("DOWN_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDownStatusIsNotNull() {
            addCriterion("DOWN_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDownStatusEqualTo(String value) {
            addCriterion("DOWN_STATUS =", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotEqualTo(String value) {
            addCriterion("DOWN_STATUS <>", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusGreaterThan(String value) {
            addCriterion("DOWN_STATUS >", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusGreaterThanOrEqualTo(String value) {
            addCriterion("DOWN_STATUS >=", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusLessThan(String value) {
            addCriterion("DOWN_STATUS <", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusLessThanOrEqualTo(String value) {
            addCriterion("DOWN_STATUS <=", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusLike(String value) {
            addCriterion("DOWN_STATUS like", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotLike(String value) {
            addCriterion("DOWN_STATUS not like", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusIn(List<String> values) {
            addCriterion("DOWN_STATUS in", values, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotIn(List<String> values) {
            addCriterion("DOWN_STATUS not in", values, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusBetween(String value1, String value2) {
            addCriterion("DOWN_STATUS between", value1, value2, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotBetween(String value1, String value2) {
            addCriterion("DOWN_STATUS not between", value1, value2, "downStatus");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("CHECK_ID is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("CHECK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("CHECK_ID =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("CHECK_ID <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("CHECK_ID >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_ID >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("CHECK_ID <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("CHECK_ID <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("CHECK_ID like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("CHECK_ID not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("CHECK_ID in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("CHECK_ID not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("CHECK_ID between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("CHECK_ID not between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckNameIsNull() {
            addCriterion("CHECK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCheckNameIsNotNull() {
            addCriterion("CHECK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCheckNameEqualTo(String value) {
            addCriterion("CHECK_NAME =", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotEqualTo(String value) {
            addCriterion("CHECK_NAME <>", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameGreaterThan(String value) {
            addCriterion("CHECK_NAME >", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_NAME >=", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLessThan(String value) {
            addCriterion("CHECK_NAME <", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLessThanOrEqualTo(String value) {
            addCriterion("CHECK_NAME <=", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLike(String value) {
            addCriterion("CHECK_NAME like", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotLike(String value) {
            addCriterion("CHECK_NAME not like", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameIn(List<String> values) {
            addCriterion("CHECK_NAME in", values, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotIn(List<String> values) {
            addCriterion("CHECK_NAME not in", values, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameBetween(String value1, String value2) {
            addCriterion("CHECK_NAME between", value1, value2, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotBetween(String value1, String value2) {
            addCriterion("CHECK_NAME not between", value1, value2, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNull() {
            addCriterion("CHECK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNotNull() {
            addCriterion("CHECK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDateEqualTo(Date value) {
            addCriterion("CHECK_DATE =", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotEqualTo(Date value) {
            addCriterion("CHECK_DATE <>", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThan(Date value) {
            addCriterion("CHECK_DATE >", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CHECK_DATE >=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThan(Date value) {
            addCriterion("CHECK_DATE <", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThanOrEqualTo(Date value) {
            addCriterion("CHECK_DATE <=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateIn(List<Date> values) {
            addCriterion("CHECK_DATE in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotIn(List<Date> values) {
            addCriterion("CHECK_DATE not in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateBetween(Date value1, Date value2) {
            addCriterion("CHECK_DATE between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotBetween(Date value1, Date value2) {
            addCriterion("CHECK_DATE not between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNull() {
            addCriterion("BANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNotNull() {
            addCriterion("BANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBankcodeEqualTo(String value) {
            addCriterion("BANKCODE =", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotEqualTo(String value) {
            addCriterion("BANKCODE <>", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThan(String value) {
            addCriterion("BANKCODE >", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANKCODE >=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThan(String value) {
            addCriterion("BANKCODE <", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThanOrEqualTo(String value) {
            addCriterion("BANKCODE <=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLike(String value) {
            addCriterion("BANKCODE like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotLike(String value) {
            addCriterion("BANKCODE not like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeIn(List<String> values) {
            addCriterion("BANKCODE in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotIn(List<String> values) {
            addCriterion("BANKCODE not in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeBetween(String value1, String value2) {
            addCriterion("BANKCODE between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotBetween(String value1, String value2) {
            addCriterion("BANKCODE not between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeIsNull() {
            addCriterion("OPCODE is null");
            return (Criteria) this;
        }

        public Criteria andOpcodeIsNotNull() {
            addCriterion("OPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andOpcodeEqualTo(String value) {
            addCriterion("OPCODE =", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotEqualTo(String value) {
            addCriterion("OPCODE <>", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeGreaterThan(String value) {
            addCriterion("OPCODE >", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("OPCODE >=", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLessThan(String value) {
            addCriterion("OPCODE <", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLessThanOrEqualTo(String value) {
            addCriterion("OPCODE <=", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLike(String value) {
            addCriterion("OPCODE like", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotLike(String value) {
            addCriterion("OPCODE not like", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeIn(List<String> values) {
            addCriterion("OPCODE in", values, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotIn(List<String> values) {
            addCriterion("OPCODE not in", values, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeBetween(String value1, String value2) {
            addCriterion("OPCODE between", value1, value2, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotBetween(String value1, String value2) {
            addCriterion("OPCODE not between", value1, value2, "opcode");
            return (Criteria) this;
        }

        public Criteria andLogdateIsNull() {
            addCriterion("LOGDATE is null");
            return (Criteria) this;
        }

        public Criteria andLogdateIsNotNull() {
            addCriterion("LOGDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLogdateEqualTo(Date value) {
            addCriterion("LOGDATE =", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotEqualTo(Date value) {
            addCriterion("LOGDATE <>", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateGreaterThan(Date value) {
            addCriterion("LOGDATE >", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGDATE >=", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateLessThan(Date value) {
            addCriterion("LOGDATE <", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateLessThanOrEqualTo(Date value) {
            addCriterion("LOGDATE <=", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateIn(List<Date> values) {
            addCriterion("LOGDATE in", values, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotIn(List<Date> values) {
            addCriterion("LOGDATE not in", values, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateBetween(Date value1, Date value2) {
            addCriterion("LOGDATE between", value1, value2, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotBetween(Date value1, Date value2) {
            addCriterion("LOGDATE not between", value1, value2, "logdate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 04 15:15:48 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEP.DEP_BIROUTE_LOG
     *
     * @mbggenerated Fri Nov 04 15:15:48 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}