package monitor.repository.model;

import java.util.Date;

public class DepMqLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.PKID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.SYSNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String sysnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.ACTION
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.OPERID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.OPERNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String opernam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.OPERDAT
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private Date operdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.REMARK
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_MQ_LOG.OPEROTH
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    private String operoth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.PKID
     *
     * @return the value of DEP.DEP_MQ_LOG.PKID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.PKID
     *
     * @param pkid the value for DEP.DEP_MQ_LOG.PKID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.SYSNAM
     *
     * @return the value of DEP.DEP_MQ_LOG.SYSNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getSysnam() {
        return sysnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.SYSNAM
     *
     * @param sysnam the value for DEP.DEP_MQ_LOG.SYSNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setSysnam(String sysnam) {
        this.sysnam = sysnam == null ? null : sysnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.ACTION
     *
     * @return the value of DEP.DEP_MQ_LOG.ACTION
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.ACTION
     *
     * @param action the value for DEP.DEP_MQ_LOG.ACTION
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.OPERID
     *
     * @return the value of DEP.DEP_MQ_LOG.OPERID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.OPERID
     *
     * @param operid the value for DEP.DEP_MQ_LOG.OPERID
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.OPERNAM
     *
     * @return the value of DEP.DEP_MQ_LOG.OPERNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getOpernam() {
        return opernam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.OPERNAM
     *
     * @param opernam the value for DEP.DEP_MQ_LOG.OPERNAM
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setOpernam(String opernam) {
        this.opernam = opernam == null ? null : opernam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.OPERDAT
     *
     * @return the value of DEP.DEP_MQ_LOG.OPERDAT
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public Date getOperdat() {
        return operdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.OPERDAT
     *
     * @param operdat the value for DEP.DEP_MQ_LOG.OPERDAT
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setOperdat(Date operdat) {
        this.operdat = operdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.REMARK
     *
     * @return the value of DEP.DEP_MQ_LOG.REMARK
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.REMARK
     *
     * @param remark the value for DEP.DEP_MQ_LOG.REMARK
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_MQ_LOG.OPEROTH
     *
     * @return the value of DEP.DEP_MQ_LOG.OPEROTH
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public String getOperoth() {
        return operoth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_MQ_LOG.OPEROTH
     *
     * @param operoth the value for DEP.DEP_MQ_LOG.OPEROTH
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    public void setOperoth(String operoth) {
        this.operoth = operoth == null ? null : operoth.trim();
    }
}