package dep.fmqd.repository.dao;

import dep.fmqd.repository.model.BiNotifyMessage;
import dep.fmqd.repository.model.BiNotifyMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BiNotifyMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int countByExample(BiNotifyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int deleteByExample(BiNotifyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int deleteByPrimaryKey(Long rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int insert(BiNotifyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int insertSelective(BiNotifyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    List<BiNotifyMessage> selectByExample(BiNotifyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    BiNotifyMessage selectByPrimaryKey(Long rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int updateByExampleSelective(@Param("record") BiNotifyMessage record, @Param("example") BiNotifyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int updateByExample(@Param("record") BiNotifyMessage record, @Param("example") BiNotifyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int updateByPrimaryKeySelective(BiNotifyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_MESSAGE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    int updateByPrimaryKey(BiNotifyMessage record);
}