package skyline.quartz.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.quartz.repository.model.QrtzBlobTriggers;
import skyline.quartz.repository.model.QrtzBlobTriggersExample;
import skyline.quartz.repository.model.QrtzBlobTriggersKey;

public interface QrtzBlobTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int countByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int deleteByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int deleteByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int insert(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int insertSelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    List<QrtzBlobTriggers> selectByExampleWithBLOBs(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    List<QrtzBlobTriggers> selectByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    QrtzBlobTriggers selectByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByExampleSelective(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByExample(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByPrimaryKeySelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(QrtzBlobTriggers record);
}