package skyline.quartz.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.quartz.repository.model.QrtzJobListenersExample;
import skyline.quartz.repository.model.QrtzJobListenersKey;

public interface QrtzJobListenersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int countByExample(QrtzJobListenersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int deleteByExample(QrtzJobListenersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int deleteByPrimaryKey(QrtzJobListenersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int insert(QrtzJobListenersKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int insertSelective(QrtzJobListenersKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    List<QrtzJobListenersKey> selectByExample(QrtzJobListenersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByExampleSelective(@Param("record") QrtzJobListenersKey record, @Param("example") QrtzJobListenersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_LISTENERS
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    int updateByExample(@Param("record") QrtzJobListenersKey record, @Param("example") QrtzJobListenersExample example);
}