package monitor.repository.dao;

import monitor.repository.model.DepMqLog;
import monitor.repository.model.DepMqLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DepMqLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int countByExample(DepMqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int deleteByExample(DepMqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int insert(DepMqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int insertSelective(DepMqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    List<DepMqLog> selectByExample(DepMqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int updateByExampleSelective(@Param("record") DepMqLog record, @Param("example") DepMqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP.DEP_MQ_LOG
     *
     * @mbggenerated Fri Nov 04 16:39:54 CST 2011
     */
    int updateByExample(@Param("record") DepMqLog record, @Param("example") DepMqLogExample example);
}