package skyline.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import skyline.repository.model.ActivemqMsgs;
import skyline.repository.model.ActivemqMsgsExample;

import java.math.BigDecimal;
import java.util.List;

@Component
public interface ActivemqMsgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int countByExample(ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int deleteByExample(ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int insert(ActivemqMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int insertSelective(ActivemqMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    List<ActivemqMsgs> selectByExampleWithBLOBs(ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    List<ActivemqMsgs> selectByExample(ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    ActivemqMsgs selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByExampleSelective(@Param("record") ActivemqMsgs record, @Param("example") ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") ActivemqMsgs record, @Param("example") ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByExample(@Param("record") ActivemqMsgs record, @Param("example") ActivemqMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByPrimaryKeySelective(ActivemqMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(ActivemqMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVEMQ_MSGS
     *
     * @mbggenerated Fri Oct 28 13:00:28 CST 2011
     */
    int updateByPrimaryKey(ActivemqMsgs record);
}