package skyline.quartz.repository.model;

public class QrtzLocks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String lockName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_LOCKS.LOCK_NAME
     *
     * @return the value of QRTZ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getLockName() {
        return lockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_LOCKS.LOCK_NAME
     *
     * @param lockName the value for QRTZ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setLockName(String lockName) {
        this.lockName = lockName == null ? null : lockName.trim();
    }
}