package skyline.quartz.repository.model;

public class QrtzJobListenersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_LISTENERS.JOB_GROUP
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_LISTENERS.JOB_LISTENER
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String jobListener;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_LISTENERS.JOB_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String jobName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_LISTENERS.JOB_GROUP
     *
     * @return the value of QRTZ_JOB_LISTENERS.JOB_GROUP
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_LISTENERS.JOB_GROUP
     *
     * @param jobGroup the value for QRTZ_JOB_LISTENERS.JOB_GROUP
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_LISTENERS.JOB_LISTENER
     *
     * @return the value of QRTZ_JOB_LISTENERS.JOB_LISTENER
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getJobListener() {
        return jobListener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_LISTENERS.JOB_LISTENER
     *
     * @param jobListener the value for QRTZ_JOB_LISTENERS.JOB_LISTENER
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setJobListener(String jobListener) {
        this.jobListener = jobListener == null ? null : jobListener.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_LISTENERS.JOB_NAME
     *
     * @return the value of QRTZ_JOB_LISTENERS.JOB_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_LISTENERS.JOB_NAME
     *
     * @param jobName the value for QRTZ_JOB_LISTENERS.JOB_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }
}