package skyline.quartz.repository.model;

public class QrtzSchedulerState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private Long checkinInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @param instanceName the value for QRTZ_SCHEDULER_STATE.INSTANCE_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @return the value of QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}