package skyline.quartz.repository.model;

public class QrtzJobDetails extends QrtzJobDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String jobClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String isDurable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_VOLATILE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String isVolatile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.IS_STATEFUL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String isStateful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    private byte[] jobData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @return the value of QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @param description the value for QRTZ_JOB_DETAILS.DESCRIPTION
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @param jobClassName the value for QRTZ_JOB_DETAILS.JOB_CLASS_NAME
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName == null ? null : jobClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @param isDurable the value for QRTZ_JOB_DETAILS.IS_DURABLE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable == null ? null : isDurable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_VOLATILE
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_VOLATILE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getIsVolatile() {
        return isVolatile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_VOLATILE
     *
     * @param isVolatile the value for QRTZ_JOB_DETAILS.IS_VOLATILE
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setIsVolatile(String isVolatile) {
        this.isVolatile = isVolatile == null ? null : isVolatile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.IS_STATEFUL
     *
     * @return the value of QRTZ_JOB_DETAILS.IS_STATEFUL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getIsStateful() {
        return isStateful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.IS_STATEFUL
     *
     * @param isStateful the value for QRTZ_JOB_DETAILS.IS_STATEFUL
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setIsStateful(String isStateful) {
        this.isStateful = isStateful == null ? null : isStateful.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @return the value of QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @param jobData the value for QRTZ_JOB_DETAILS.JOB_DATA
     *
     * @mbggenerated Tue Nov 22 13:18:46 CST 2011
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}