package dep.fmqd.repository.model;

import java.util.Date;

public class BiNotifyAcctstatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.NOTIFY_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String opcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String acct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCTNAME
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String acctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.STATUS
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.BALANCE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.LOCKAMT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String lockamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String getFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Integer modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String getMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ROW_ID
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ROW_ID
     *
     * @param rowId the value for FMDB.BI_NOTIFY_ACCTSTATUS.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.NOTIFY_ID
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.NOTIFY_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.NOTIFY_ID
     *
     * @param notifyId the value for FMDB.BI_NOTIFY_ACCTSTATUS.NOTIFY_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setNotifyId(Long notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.OPCODE
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getOpcode() {
        return opcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.OPCODE
     *
     * @param opcode the value for FMDB.BI_NOTIFY_ACCTSTATUS.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setOpcode(String opcode) {
        this.opcode = opcode == null ? null : opcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.BANKCODE
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.BANKCODE
     *
     * @param bankcode the value for FMDB.BI_NOTIFY_ACCTSTATUS.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCT
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.ACCT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getAcct() {
        return acct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCT
     *
     * @param acct the value for FMDB.BI_NOTIFY_ACCTSTATUS.ACCT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setAcct(String acct) {
        this.acct = acct == null ? null : acct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCTNAME
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.ACCTNAME
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getAcctname() {
        return acctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.ACCTNAME
     *
     * @param acctname the value for FMDB.BI_NOTIFY_ACCTSTATUS.ACCTNAME
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setAcctname(String acctname) {
        this.acctname = acctname == null ? null : acctname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.STATUS
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.STATUS
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.STATUS
     *
     * @param status the value for FMDB.BI_NOTIFY_ACCTSTATUS.STATUS
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.BALANCE
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.BALANCE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.BALANCE
     *
     * @param balance the value for FMDB.BI_NOTIFY_ACCTSTATUS.BALANCE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LOCKAMT
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.LOCKAMT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getLockamt() {
        return lockamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LOCKAMT
     *
     * @param lockamt the value for FMDB.BI_NOTIFY_ACCTSTATUS.LOCKAMT
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setLockamt(String lockamt) {
        this.lockamt = lockamt == null ? null : lockamt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_FLAG
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getGetFlag() {
        return getFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_FLAG
     *
     * @param getFlag the value for FMDB.BI_NOTIFY_ACCTSTATUS.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setGetFlag(String getFlag) {
        this.getFlag = getFlag == null ? null : getFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_BY
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_BY
     *
     * @param createdBy the value for FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_DATE
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_DATE
     *
     * @param createdDate the value for FMDB.BI_NOTIFY_ACCTSTATUS.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_BY
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_BY
     *
     * @param lastUpdBy the value for FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setLastUpdBy(Long lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_DATE
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for FMDB.BI_NOTIFY_ACCTSTATUS.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.MODIFICATION_NUM
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.MODIFICATION_NUM
     *
     * @param modificationNum the value for FMDB.BI_NOTIFY_ACCTSTATUS.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.DELETED_FLAG
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.DELETED_FLAG
     *
     * @param deletedFlag the value for FMDB.BI_NOTIFY_ACCTSTATUS.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_MSG
     *
     * @return the value of FMDB.BI_NOTIFY_ACCTSTATUS.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getGetMsg() {
        return getMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_ACCTSTATUS.GET_MSG
     *
     * @param getMsg the value for FMDB.BI_NOTIFY_ACCTSTATUS.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setGetMsg(String getMsg) {
        this.getMsg = getMsg == null ? null : getMsg.trim();
    }
}