package dep.fmqd.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BiNotifyDishonourExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public BiNotifyDishonourExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRowIdIsNull() {
            addCriterion("ROW_ID is null");
            return (Criteria) this;
        }

        public Criteria andRowIdIsNotNull() {
            addCriterion("ROW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRowIdEqualTo(Long value) {
            addCriterion("ROW_ID =", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotEqualTo(Long value) {
            addCriterion("ROW_ID <>", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdGreaterThan(Long value) {
            addCriterion("ROW_ID >", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ROW_ID >=", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdLessThan(Long value) {
            addCriterion("ROW_ID <", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdLessThanOrEqualTo(Long value) {
            addCriterion("ROW_ID <=", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdIn(List<Long> values) {
            addCriterion("ROW_ID in", values, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotIn(List<Long> values) {
            addCriterion("ROW_ID not in", values, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdBetween(Long value1, Long value2) {
            addCriterion("ROW_ID between", value1, value2, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotBetween(Long value1, Long value2) {
            addCriterion("ROW_ID not between", value1, value2, "rowId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdIsNull() {
            addCriterion("NOTIFY_ID is null");
            return (Criteria) this;
        }

        public Criteria andNotifyIdIsNotNull() {
            addCriterion("NOTIFY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyIdEqualTo(Long value) {
            addCriterion("NOTIFY_ID =", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdNotEqualTo(Long value) {
            addCriterion("NOTIFY_ID <>", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdGreaterThan(Long value) {
            addCriterion("NOTIFY_ID >", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("NOTIFY_ID >=", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdLessThan(Long value) {
            addCriterion("NOTIFY_ID <", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdLessThanOrEqualTo(Long value) {
            addCriterion("NOTIFY_ID <=", value, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdIn(List<Long> values) {
            addCriterion("NOTIFY_ID in", values, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdNotIn(List<Long> values) {
            addCriterion("NOTIFY_ID not in", values, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdBetween(Long value1, Long value2) {
            addCriterion("NOTIFY_ID between", value1, value2, "notifyId");
            return (Criteria) this;
        }

        public Criteria andNotifyIdNotBetween(Long value1, Long value2) {
            addCriterion("NOTIFY_ID not between", value1, value2, "notifyId");
            return (Criteria) this;
        }

        public Criteria andOpcodeIsNull() {
            addCriterion("OPCODE is null");
            return (Criteria) this;
        }

        public Criteria andOpcodeIsNotNull() {
            addCriterion("OPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andOpcodeEqualTo(String value) {
            addCriterion("OPCODE =", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotEqualTo(String value) {
            addCriterion("OPCODE <>", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeGreaterThan(String value) {
            addCriterion("OPCODE >", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("OPCODE >=", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLessThan(String value) {
            addCriterion("OPCODE <", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLessThanOrEqualTo(String value) {
            addCriterion("OPCODE <=", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeLike(String value) {
            addCriterion("OPCODE like", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotLike(String value) {
            addCriterion("OPCODE not like", value, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeIn(List<String> values) {
            addCriterion("OPCODE in", values, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotIn(List<String> values) {
            addCriterion("OPCODE not in", values, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeBetween(String value1, String value2) {
            addCriterion("OPCODE between", value1, value2, "opcode");
            return (Criteria) this;
        }

        public Criteria andOpcodeNotBetween(String value1, String value2) {
            addCriterion("OPCODE not between", value1, value2, "opcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNull() {
            addCriterion("BANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNotNull() {
            addCriterion("BANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBankcodeEqualTo(String value) {
            addCriterion("BANKCODE =", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotEqualTo(String value) {
            addCriterion("BANKCODE <>", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThan(String value) {
            addCriterion("BANKCODE >", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANKCODE >=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThan(String value) {
            addCriterion("BANKCODE <", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThanOrEqualTo(String value) {
            addCriterion("BANKCODE <=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLike(String value) {
            addCriterion("BANKCODE like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotLike(String value) {
            addCriterion("BANKCODE not like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeIn(List<String> values) {
            addCriterion("BANKCODE in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotIn(List<String> values) {
            addCriterion("BANKCODE not in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeBetween(String value1, String value2) {
            addCriterion("BANKCODE between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotBetween(String value1, String value2) {
            addCriterion("BANKCODE not between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andAcctIsNull() {
            addCriterion("ACCT is null");
            return (Criteria) this;
        }

        public Criteria andAcctIsNotNull() {
            addCriterion("ACCT is not null");
            return (Criteria) this;
        }

        public Criteria andAcctEqualTo(String value) {
            addCriterion("ACCT =", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctNotEqualTo(String value) {
            addCriterion("ACCT <>", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctGreaterThan(String value) {
            addCriterion("ACCT >", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT >=", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctLessThan(String value) {
            addCriterion("ACCT <", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctLessThanOrEqualTo(String value) {
            addCriterion("ACCT <=", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctLike(String value) {
            addCriterion("ACCT like", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctNotLike(String value) {
            addCriterion("ACCT not like", value, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctIn(List<String> values) {
            addCriterion("ACCT in", values, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctNotIn(List<String> values) {
            addCriterion("ACCT not in", values, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctBetween(String value1, String value2) {
            addCriterion("ACCT between", value1, value2, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctNotBetween(String value1, String value2) {
            addCriterion("ACCT not between", value1, value2, "acct");
            return (Criteria) this;
        }

        public Criteria andAcctnameIsNull() {
            addCriterion("ACCTNAME is null");
            return (Criteria) this;
        }

        public Criteria andAcctnameIsNotNull() {
            addCriterion("ACCTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andAcctnameEqualTo(String value) {
            addCriterion("ACCTNAME =", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotEqualTo(String value) {
            addCriterion("ACCTNAME <>", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameGreaterThan(String value) {
            addCriterion("ACCTNAME >", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameGreaterThanOrEqualTo(String value) {
            addCriterion("ACCTNAME >=", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLessThan(String value) {
            addCriterion("ACCTNAME <", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLessThanOrEqualTo(String value) {
            addCriterion("ACCTNAME <=", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLike(String value) {
            addCriterion("ACCTNAME like", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotLike(String value) {
            addCriterion("ACCTNAME not like", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameIn(List<String> values) {
            addCriterion("ACCTNAME in", values, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotIn(List<String> values) {
            addCriterion("ACCTNAME not in", values, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameBetween(String value1, String value2) {
            addCriterion("ACCTNAME between", value1, value2, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotBetween(String value1, String value2) {
            addCriterion("ACCTNAME not between", value1, value2, "acctname");
            return (Criteria) this;
        }

        public Criteria andBankserialIsNull() {
            addCriterion("BANKSERIAL is null");
            return (Criteria) this;
        }

        public Criteria andBankserialIsNotNull() {
            addCriterion("BANKSERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andBankserialEqualTo(String value) {
            addCriterion("BANKSERIAL =", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialNotEqualTo(String value) {
            addCriterion("BANKSERIAL <>", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialGreaterThan(String value) {
            addCriterion("BANKSERIAL >", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialGreaterThanOrEqualTo(String value) {
            addCriterion("BANKSERIAL >=", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialLessThan(String value) {
            addCriterion("BANKSERIAL <", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialLessThanOrEqualTo(String value) {
            addCriterion("BANKSERIAL <=", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialLike(String value) {
            addCriterion("BANKSERIAL like", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialNotLike(String value) {
            addCriterion("BANKSERIAL not like", value, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialIn(List<String> values) {
            addCriterion("BANKSERIAL in", values, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialNotIn(List<String> values) {
            addCriterion("BANKSERIAL not in", values, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialBetween(String value1, String value2) {
            addCriterion("BANKSERIAL between", value1, value2, "bankserial");
            return (Criteria) this;
        }

        public Criteria andBankserialNotBetween(String value1, String value2) {
            addCriterion("BANKSERIAL not between", value1, value2, "bankserial");
            return (Criteria) this;
        }

        public Criteria andTradedateIsNull() {
            addCriterion("TRADEDATE is null");
            return (Criteria) this;
        }

        public Criteria andTradedateIsNotNull() {
            addCriterion("TRADEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradedateEqualTo(String value) {
            addCriterion("TRADEDATE =", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateNotEqualTo(String value) {
            addCriterion("TRADEDATE <>", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateGreaterThan(String value) {
            addCriterion("TRADEDATE >", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateGreaterThanOrEqualTo(String value) {
            addCriterion("TRADEDATE >=", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateLessThan(String value) {
            addCriterion("TRADEDATE <", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateLessThanOrEqualTo(String value) {
            addCriterion("TRADEDATE <=", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateLike(String value) {
            addCriterion("TRADEDATE like", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateNotLike(String value) {
            addCriterion("TRADEDATE not like", value, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateIn(List<String> values) {
            addCriterion("TRADEDATE in", values, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateNotIn(List<String> values) {
            addCriterion("TRADEDATE not in", values, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateBetween(String value1, String value2) {
            addCriterion("TRADEDATE between", value1, value2, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradedateNotBetween(String value1, String value2) {
            addCriterion("TRADEDATE not between", value1, value2, "tradedate");
            return (Criteria) this;
        }

        public Criteria andTradetimeIsNull() {
            addCriterion("TRADETIME is null");
            return (Criteria) this;
        }

        public Criteria andTradetimeIsNotNull() {
            addCriterion("TRADETIME is not null");
            return (Criteria) this;
        }

        public Criteria andTradetimeEqualTo(String value) {
            addCriterion("TRADETIME =", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeNotEqualTo(String value) {
            addCriterion("TRADETIME <>", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeGreaterThan(String value) {
            addCriterion("TRADETIME >", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADETIME >=", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeLessThan(String value) {
            addCriterion("TRADETIME <", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeLessThanOrEqualTo(String value) {
            addCriterion("TRADETIME <=", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeLike(String value) {
            addCriterion("TRADETIME like", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeNotLike(String value) {
            addCriterion("TRADETIME not like", value, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeIn(List<String> values) {
            addCriterion("TRADETIME in", values, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeNotIn(List<String> values) {
            addCriterion("TRADETIME not in", values, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeBetween(String value1, String value2) {
            addCriterion("TRADETIME between", value1, value2, "tradetime");
            return (Criteria) this;
        }

        public Criteria andTradetimeNotBetween(String value1, String value2) {
            addCriterion("TRADETIME not between", value1, value2, "tradetime");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("REASON is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("REASON is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("REASON =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("REASON <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("REASON >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("REASON >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("REASON <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("REASON <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("REASON like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("REASON not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("REASON in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("REASON not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("REASON between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("REASON not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andGetFlagIsNull() {
            addCriterion("GET_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andGetFlagIsNotNull() {
            addCriterion("GET_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andGetFlagEqualTo(String value) {
            addCriterion("GET_FLAG =", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagNotEqualTo(String value) {
            addCriterion("GET_FLAG <>", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagGreaterThan(String value) {
            addCriterion("GET_FLAG >", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagGreaterThanOrEqualTo(String value) {
            addCriterion("GET_FLAG >=", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagLessThan(String value) {
            addCriterion("GET_FLAG <", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagLessThanOrEqualTo(String value) {
            addCriterion("GET_FLAG <=", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagLike(String value) {
            addCriterion("GET_FLAG like", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagNotLike(String value) {
            addCriterion("GET_FLAG not like", value, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagIn(List<String> values) {
            addCriterion("GET_FLAG in", values, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagNotIn(List<String> values) {
            addCriterion("GET_FLAG not in", values, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagBetween(String value1, String value2) {
            addCriterion("GET_FLAG between", value1, value2, "getFlag");
            return (Criteria) this;
        }

        public Criteria andGetFlagNotBetween(String value1, String value2) {
            addCriterion("GET_FLAG not between", value1, value2, "getFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(Long value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(Long value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(Long value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(Long value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(Long value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<Long> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<Long> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(Long value1, Long value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(Long value1, Long value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNull() {
            addCriterion("LAST_UPD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNotNull() {
            addCriterion("LAST_UPD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE =", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <>", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThan(Date value) {
            addCriterion("LAST_UPD_DATE >", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE >=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThan(Date value) {
            addCriterion("LAST_UPD_DATE <", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE not in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE not between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNull() {
            addCriterion("MODIFICATION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNotNull() {
            addCriterion("MODIFICATION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andModificationNumEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM =", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <>", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThan(Integer value) {
            addCriterion("MODIFICATION_NUM >", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM >=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThan(Integer value) {
            addCriterion("MODIFICATION_NUM <", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM not in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM not between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("DELETED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("DELETED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(String value) {
            addCriterion("DELETED_FLAG =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(String value) {
            addCriterion("DELETED_FLAG <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(String value) {
            addCriterion("DELETED_FLAG >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETED_FLAG >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(String value) {
            addCriterion("DELETED_FLAG <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETED_FLAG <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLike(String value) {
            addCriterion("DELETED_FLAG like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotLike(String value) {
            addCriterion("DELETED_FLAG not like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<String> values) {
            addCriterion("DELETED_FLAG in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<String> values) {
            addCriterion("DELETED_FLAG not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(String value1, String value2) {
            addCriterion("DELETED_FLAG between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(String value1, String value2) {
            addCriterion("DELETED_FLAG not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andGetMsgIsNull() {
            addCriterion("GET_MSG is null");
            return (Criteria) this;
        }

        public Criteria andGetMsgIsNotNull() {
            addCriterion("GET_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andGetMsgEqualTo(String value) {
            addCriterion("GET_MSG =", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgNotEqualTo(String value) {
            addCriterion("GET_MSG <>", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgGreaterThan(String value) {
            addCriterion("GET_MSG >", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgGreaterThanOrEqualTo(String value) {
            addCriterion("GET_MSG >=", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgLessThan(String value) {
            addCriterion("GET_MSG <", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgLessThanOrEqualTo(String value) {
            addCriterion("GET_MSG <=", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgLike(String value) {
            addCriterion("GET_MSG like", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgNotLike(String value) {
            addCriterion("GET_MSG not like", value, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgIn(List<String> values) {
            addCriterion("GET_MSG in", values, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgNotIn(List<String> values) {
            addCriterion("GET_MSG not in", values, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgBetween(String value1, String value2) {
            addCriterion("GET_MSG between", value1, value2, "getMsg");
            return (Criteria) this;
        }

        public Criteria andGetMsgNotBetween(String value1, String value2) {
            addCriterion("GET_MSG not between", value1, value2, "getMsg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 29 14:37:20 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FMDB.BI_NOTIFY_DISHONOUR
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}