package dep.fmqd.repository.model;

import java.util.Date;

public class BiNotifyMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String opcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.NOTIFYDATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Date notifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String getFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Long lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private Integer modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FMDB.BI_NOTIFY_MESSAGE.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    private String getMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.ROW_ID
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.ROW_ID
     *
     * @param rowId the value for FMDB.BI_NOTIFY_MESSAGE.ROW_ID
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.OPCODE
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getOpcode() {
        return opcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.OPCODE
     *
     * @param opcode the value for FMDB.BI_NOTIFY_MESSAGE.OPCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setOpcode(String opcode) {
        this.opcode = opcode == null ? null : opcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.BANKCODE
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.BANKCODE
     *
     * @param bankcode the value for FMDB.BI_NOTIFY_MESSAGE.BANKCODE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.NOTIFYDATE
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.NOTIFYDATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Date getNotifydate() {
        return notifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.NOTIFYDATE
     *
     * @param notifydate the value for FMDB.BI_NOTIFY_MESSAGE.NOTIFYDATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setNotifydate(Date notifydate) {
        this.notifydate = notifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.GET_FLAG
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getGetFlag() {
        return getFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.GET_FLAG
     *
     * @param getFlag the value for FMDB.BI_NOTIFY_MESSAGE.GET_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setGetFlag(String getFlag) {
        this.getFlag = getFlag == null ? null : getFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_BY
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_BY
     *
     * @param createdBy the value for FMDB.BI_NOTIFY_MESSAGE.CREATED_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_DATE
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.CREATED_DATE
     *
     * @param createdDate the value for FMDB.BI_NOTIFY_MESSAGE.CREATED_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_BY
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Long getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_BY
     *
     * @param lastUpdBy the value for FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_BY
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setLastUpdBy(Long lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_DATE
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for FMDB.BI_NOTIFY_MESSAGE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.MODIFICATION_NUM
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.MODIFICATION_NUM
     *
     * @param modificationNum the value for FMDB.BI_NOTIFY_MESSAGE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.DELETED_FLAG
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.DELETED_FLAG
     *
     * @param deletedFlag the value for FMDB.BI_NOTIFY_MESSAGE.DELETED_FLAG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMDB.BI_NOTIFY_MESSAGE.GET_MSG
     *
     * @return the value of FMDB.BI_NOTIFY_MESSAGE.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public String getGetMsg() {
        return getMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMDB.BI_NOTIFY_MESSAGE.GET_MSG
     *
     * @param getMsg the value for FMDB.BI_NOTIFY_MESSAGE.GET_MSG
     *
     * @mbggenerated Thu Sep 29 14:37:20 CST 2011
     */
    public void setGetMsg(String getMsg) {
        this.getMsg = getMsg == null ? null : getMsg.trim();
    }
}